In [3]:
import pandas as pd
import quandl

In [7]:
quandl.ApiConfig.api_key = 'ehaNF1HJ48yvsbbVWoyh'
df = quandl.get('NASDAQOMX/NQSE35CAD')
df

,Index Value,High,Low,Total Market Value,Dividend Market Value
Trade Date,,,,,
2020-09-21,968.82,968.82,968.82,4.686191e+10,0.0
2020-09-22,961.83,961.83,961.83,4.652360e+10,0.0
2020-09-23,952.87,952.87,952.87,4.609019e+10,0.0
2020-09-24,942.21,942.21,942.21,4.557474e+10,0.0
2020-09-25,949.03,949.03,949.03,4.590459e+10,0.0
...,...,...,...,...,...
2021-03-23,966.70,966.70,966.70,4.905023e+10,0.0
2021-03-24,966.19,966.19,966.19,4.902403e+10,0.0
2021-03-25,952.75,952.75,952.75,4.834220e+10,82911343.0
2021-03-26,947.90,947.90,947.90,4.809594e+10,254301821.0
2021-03-30,NaN,0.00,0.00,NaN,50276908.0